apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:0b32e6d32808448d3a64f4703767ab9ebfd0a08643fed3eeced43635f1b7f5b1
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
