apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:93405e382137e1b7f98417997f98b85220b7b7e5149e4266a710a341e3d16fa4
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
