apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9ec12922f704fd1b427500379534f4bd448b6ba9372b725b62d828ba4fca74e7
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:fdac8e7770a35fc24d20d71ef94e111f4e662ce06e2e4d8273eb58ce12a4c5b2
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
