apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:d9c23d29398b125a8ae2bda43bc4b593b593890e08f46493143c8c1ca00d1df6
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
