apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:fbaa9661625e0ba016a58ebe80c6c53c9cd3ceb5b93decb6e3b2549dfafd3173
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
