apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:72d60104ad6d435fdd6acf88930328f6ce3993c5597aabf554482d3410becf2a
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
- digest: sha256:306edc748117fc74babee49686db911e22504349de5e0507ac013dc63a393560
  name: quay.io/dleong/vote-api
  newName: quay.io/dleong/vote-api
- digest: sha256:e47e46c5080d2c6790df82a00cdd7f58a48344fc2218a5acfa819e8bcd0d16bb
  name: quay.io/dleong/vote-ui
  newName: quay.io/dleong/vote-ui
