apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:7bdab6325a9631d4bacef6a73fe5d7b6f02ed0407caba5d4c8ccbe2ad6daf66b
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
