apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:8c2ba591e9a70f1a308458e65bc0018ddb4145da5195c457cfbeb6e16e8908c6
  name: quay.io/dleong/vote-api
  newName: quay.io/dleong/vote-api
- digest: sha256:9877e31e74eccdd14095b0c5ca384f835c74f0bd1e13174f9217b64e46243ec6
  name: quay.io/dleong/vote-ui
  newName: quay.io/dleong/vote-ui
