apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:c89721e20a2761291f8935c6f1fd5c82501a9ba6b40e0f6988580b6d46342060
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
