apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9e8b1b5bcf99c00664a7e389ff6201a1657623730579f07cf9c85de4e8dfe832
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
