apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9857da4ee34dc1378bef9a8730dc8e34ada76f30fb3ab58925ab02fc15f3b73f
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:146a70310dc4e86839e633bbd43e0921de76f12b104ee3d5de46546b6651712c
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
