apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:2269147e44ea36a789b004f23ceb0ddc66b83993aa7f615b10c10ab9f77d11c5
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:007f92ecb1e1889c4138cbc13b68a492522028945e4d15655b9f72496653947e
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
