apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:9857da4ee34dc1378bef9a8730dc8e34ada76f30fb3ab58925ab02fc15f3b73f
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:54f7dcfd077f8b83f5bad31f393292d7ce878e5e5d4514b4973fdcb79d800f21
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
