apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:780e0240bda0f8b80ff2467c9f673d7a6974b94f74d085ae0fe082974ffb0a00
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
