apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:a1f1fa30242addc2174b18e901823641c4ff0328541a8f5834ab9df59f1eabd0
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
